apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deplyment
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name: vai
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: ubuntu/apache2
        ports:
        -  containerPort: 80
