apiVersion: v1
kind: Service
metadata:
 name: my-nginx-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 80   # in container
      port: 80   #  nodeport
      #nodePort: 30008
  selector:
    app: nginx       
